### PR TITLE
Fixed ALLOWED_HOSTS settings and redirected email to stdout, to stop …

### PR DESCRIPTION
**Pull request by darthryking**
…email misconfiguration errors

### CODE REVIEW

**Comment by cheryllium** [comment]
@darthryking thnx but is it still redirecting my emails to stdout

cuz maybe i still want to get emailed about if russian haxx0rs try to take my site down...

**Comment by darthryking** [comment]
Errr unless you subscribe to a third-party emailing service, or set up your own personal SMTP server, you won't be able to get emails anyway.

**Comment by cheryllium** [comment]
@darthryking what do we typically use now for mail though, sendgrid? I forget what we used for mailapunch as opposed to jumble (or did we switch jumble over? halp im forgetting everything)

**Comment by darthryking** [comment]
Yeah we use Sendgrid for basically everything now that Mandrill is defunct.

**Pull request merged**
